# Generated by Django 4.2.23 on 2025-08-16 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_delete_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('technical', 'Technical'), ('soft', 'Soft'), ('other', 'Other')], default='technical', max_length=50),
        ),
    ]
