# Generated by Django 4.2.23 on 2025-08-27 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0004_alter_job_source'),
        ('candidates', '0002_candidate_interested_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchExplanation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explanation', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidates.candidate')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.job')),
            ],
            options={
                'unique_together': {('candidate', 'job')},
            },
        ),
    ]
