SKILL_KEYWORDS = {
    "Python": ["python"],
    "Django": ["django"],
    "React": ["react", "reactjs", "react.js"],
    "Node.js": ["node", "nodejs", "node.js"],
    "SQL": ["sql", "mysql", "postgres", "postgresql"],
    "AWS": ["aws", "amazon web services"],
    "Docker": ["docker"],
    "Kubernetes": ["kubernetes", "k8s"],
    "Machine Learning": ["machine learning", "ml"],
    "Deep Learning": ["deep learning", "dl"],
    "Natural Language Processing": ["natural language processing", "nlp"],
    "Computer Vision": ["computer vision", "cv"],
    "Data Science": ["data science", "data analysis", "data scientist"],
    "Big Data": ["big data", "hadoop", "spark"],
    "Cloud Computing": ["cloud computing", "cloud", "aws", "azure", "google cloud"],
    "DevOps": ["devops", "docker", "kubernetes", "ci/cd"],
    "Cybersecurity": ["cybersecurity", "security", "infosec"],
    "Internet of Things": ["iot", "internet of things"],
    "Blockchain": ["blockchain", "crypto", "cryptocurrency"],
    "Java": ["java", "javac", "jdk"],
    "Go": ["go", "golang"],
    "JavaScript": ["javascript", "js"],
    "TypeScript": ["typescript", "ts"],
    "PHP": ["php"],
    "Ruby": ["ruby", "rails"],
    "Swift": ["swift"],
    "Kotlin": ["kotlin"],
}
