# Generated by Django 4.2.23 on 2025-08-20 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='interested_roles',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
