# Generated by Django 4.2.23 on 2025-08-16 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_candidate_improvement_tips_candidate_profile_summary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='user',
        ),
        migrations.AddField(
            model_name='candidate',
            name='desired_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='location_preference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
