# Generated by Django 4.2.23 on 2025-08-14 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_delete_jobapplication'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='skills',
            field=models.ManyToManyField(db_index=True, related_name='jobs', to='core.skill'),
        ),
    ]
