# Generated by Django 4.2.23 on 2025-08-21 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='source',
            field=models.CharField(choices=[('internal', 'Internal'), ('indiapai', 'IndiaAPI')], db_index=True, default='internal', max_length=50),
        ),
    ]
