# Generated by Django 4.2.23 on 2025-08-16 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_job_is_active_alter_job_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='posted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='source',
            field=models.CharField(choices=[('internal', 'Internal'), ('jooble', 'Jooble'), ('adzuna', 'Adzuna'), ('usajobs', 'USAJobs')], db_index=True, default='internal', max_length=50),
        ),
        migrations.AddField(
            model_name='job',
            name='source_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
