# Generated by Django 4.2.23 on 2025-08-21 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_job_employment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='source',
            field=models.CharField(choices=[('internal', 'Internal'), ('indianapi', 'IndianAPI')], db_index=True, default='internal', max_length=50),
        ),
    ]
