# Generated by Django 4.2.23 on 2025-08-24 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0004_alter_job_source'),
        ('candidates', '0002_candidate_interested_roles'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidates.candidate')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.job')),
            ],
        ),
        migrations.CreateModel(
            name='LearningResources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('platform', models.CharField(choices=[('udemy', 'Udemy'), ('youtube', 'YouTube'), ('coursera', 'Coursera'), ('github', 'GitHub'), ('doc', 'Official Docs'), ('whitepaper', 'Whitepaper')], default='youtube', max_length=50)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=50)),
                ('duration_hours', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('skills', models.ManyToManyField(related_name='learning_resources', to='core.skill')),
            ],
        ),
        migrations.CreateModel(
            name='LearningStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('completed', models.BooleanField(default=False)),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='learning.learningpath')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.learningresources')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='learningpath',
            name='resources',
            field=models.ManyToManyField(related_name='learning_paths', to='learning.learningresources'),
        ),
    ]
